### ISSUE TITLE
Unable to initialize client

### ISSUE THREAD

**Issue by mkoser** [barolab/verdaccio-minio#1]
When using this plugin, I get the following error:
```docker
verdaccio    |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio    |  warn --- Plugin successfully loaded: verdaccio-minio-storage
verdaccio    |  debug-=- [Minio] Loading current secret
verdaccio    |  debug-=- [Minio] Loading database db.json from cache
verdaccio    |  debug-=- [Minio] Failed to ensure bucket npm exist, { Error: socket hang up
verdaccio    |     at createHangUpError (_http_client.js:323:15)
verdaccio    |     at Socket.socketOnEnd (_http_client.js:426:23)
verdaccio    |     at Socket.emit (events.js:203:15)
verdaccio    |     at endReadableNT (_stream_readable.js:1145:12)
verdaccio    |     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
verdaccio    |  error-=- There was an error initializing client: Error: Failed to ensure bucket npm exist: socket hang up
verdaccio    |     at Client.initialize (/opt/verdaccio/node_modules/verdaccio-minio/lib/client.js:84:13)
verdaccio    |     at process._tickCallback (internal/process/next_tick.js:68:7)
verdaccio    |  debug-=- [Minio] Failed to load database from remote storage, { Error: socket hang up
verdaccio    |     at createHangUpError (_http_client.js:323:15)
verdaccio    |     at Socket.socketOnEnd (_http_client.js:426:23)
verdaccio    |     at Socket.emit (events.js:203:15)
verdaccio    |     at endReadableNT (_stream_readable.js:1145:12)
verdaccio    |     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
```
As you can see I'm running this in docker-compose, but attempting to connect to an internally hosted minio cluster. 

Relevant config:
verdaccio: 4.2.2
verdaccio-minio: 0.1.5
minio: RELEASE.2019-04-09T01-22-30Z

config.yaml:
```yaml
plugins: /verdaccio/plugins
store:
  minio-storage:
    port: 443
    endPoint: minio-dev.backends.tech
    accessKey: access_key
    secretKey: secret_key
    useSSL: false
    region: us-east-1
    bucket: 'npm'
    retries: 3
    delay: 50
```
Looking at the minio logs during startup, I see no indication of authentication issues but I do see active connections from the docker host running verdaccio.
